export { default as authRoutes } from './authRoutes.ts';
export { default as userRoutes } from './userRoutes.ts';
export { default as clientRoutes } from './clientRoutes.ts';
export { default as appointmentRoutes } from './appointmentRoutes.ts';
export { default as hilfeplanRoutes } from './hilfePlanRoutes.ts';
export { default as statsRoutes } from './statsRoutes.ts';
export { default as documentRoutes } from './documentRoutes.ts';
export { default as clientDocumentRoutes } from './clientDocumentRoutes.ts';
export { default as notificationRoutes } from './notificationRoutes.ts';
